[logger]
level = "info"
messageFormat = "%(asctime)s  %(message)s"

[theme]
# Primary accent for interactive elements
primaryColor = '#228be6'
backgroundColor = 'rgb(255, 255, 255)'

This error can be resolved by making any change to .streamlit/config.toml. It doesn’t even have to contain anything (i.e. headless = true is not necessary). Just type a new line, commit it, and push it to the repo. Then I have this log